[tool.ruff]
extend-select = [
  "ASYNC",  # flake8-async
  "B",      # flake8-bugbear
  "C4",     # flake8-comprehensions
  "C90",    # McCabe cyclomatic complexity
  "DJ",     # flake8-django
  "E",      # pycodestyle errors
  "F",      # Pyflakes
  "FBT",    # flake8-boolean-trap
  "I",      # isort
  "INT",    # flake8-gettext
  "PGH",    # pygrep-hooks
  "PIE",    # flake8-pie
  "RUF100", # Unused noqa directive
  "SIM",    # flake8-simplify
  "SLOT",   # flake8-slots
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings
]
fix = true
show-fixes = true
target-version = "py312"

[tool.ruff.isort]
combine-as-imports = true
